# Generated by Django 6.0.1 on 2026-03-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
