# Generated by Django 6.0.1 on 2026-03-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_saleitem_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
    ]
